PORTNAME=		eap_parrot
PORTVERSION=		1.0.0
CATEGORIES=		net
DISTNAME=		${PORTNAME}-${ISCVERSION}
DISTVERSIONPREFIX=	v

MAINTAINER=		mark@cloudbsd.org
COMMENT=		Replay EAP packets between network interfaces
WWW=			https://github.com/cloudbsdorg/eap_parrot

LICENSE=		GPLv3

BUILD_DEPENDS=		go119:lang/go119

MASTER_SITES=		GH
USE_GITHUB=		yes
GL_SITE=		https://github.com
GH_ACCOUNT=		cloudbsdorg
GH_PROJECT=		eap_parrot

.include <bsd.port.mk>
