.Dd November 5, 2022
.Dt EAP_PARROT 1
.Os
.Sh NAME
.Nm eap_parrot
.Nd replay EAP packets between network interfaces
.Sh SYNOPSIS
.Nm eap_parrot
.Op Fl @ABCFGHILOPRSTUWabcdefghiklmnopqrstuvwxy1%\&,
.Op Fl -color Ns = Ns Ar when
.Op Fl D Ar format
.Op Ar
.SH DESCRIPTION
.P
\fBeap_parrot\fR can be used to pass Extensible Authentication Protocol (EAP) packets
a directory of images or a specified image to a single PDF file, or
expand
a single PDF file into a collection
of image files.
